$pdf_mode = 1;          # generate PDF
$bibtex_use = 1;
$silent = 1;
$max_repeat = 5;
add_cus_dep('tex','pdf',0,'do_latex');
sub do_latex { system('/usr/bin/pdflatex -interaction=nonstopmode -halt-on-error -file-line-error main.tex'); }
